# Generated by Django 3.2.12 on 2023-02-28 17:16

import django.contrib.postgres.fields
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('device_id', models.CharField(max_length=100)),
                ('analog_input', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=main.models.get_default_array, size=None)),
            ],
        ),
    ]
