# Generated by Django 3.2.12 on 2023-02-28 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="humidity",
        ),
        migrations.RemoveField(
            model_name="device",
            name="manual_mode",
        ),
        migrations.RemoveField(
            model_name="device",
            name="temperature",
        ),
    ]
