# Generated by Django 3.2.12 on 2023-02-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230228_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='moisture_level',
            new_name='analog_input',
        ),
    ]
