# Generated by Django 3.2.12 on 2023-04-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_device_verdict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='verdict',
        ),
    ]
